<div class="card">
    <div class="card-header">Inscription</div>
    <div class="card-body">
        <form action="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=account" method="post">
            <input type="hidden" name="token" value="<?= $tplVars['Token']; ?>" />
            <div class="form-group row">
                <label for="inputEmail" class="col-md-4 col-form-label text-md-right">Email</label>
                <div class="col-md-6">
                    <input type="email" id="inputEmail" name="inputEmail" class="form-control" placeholder="Email" required autofocus>
                </div>
            </div>
            <div class="form-group row">
                <label for="inputNickname" class="col-md-4 col-form-label text-md-right">Pseudo</label>
                <div class="col-md-6">
                    <input type="text" id="inputNickname" name="inputNickname" class="form-control" placeholder="Pseudo" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword" class="col-md-4 col-form-label text-md-right">Mot de passe</label>
                <div class="col-md-6">
                    <input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Mot de passe" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword2" class="col-md-4 col-form-label text-md-right">Re-saisir</label>
                <div class="col-md-6">
                    <input type="password" id="inputPassword2" name="inputPassword2" class="form-control" placeholder="Re-saisir" required>
                </div>
            </div>
            <div class="col-md-6 offset-md-4">
                <button class="w-100 btn btn-lg btn-primary" type="submit">Inscription</button>
            </div>
        </form>
        </div>
    </div>