<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Contact</title>
</head>
<body id="top">
    <main class="main container">
    <h1>Une erreur est survenue !</h1>

<p>Une erreur est survenue, merci de vous reconnecter plus tard ou de contacter un administrateur.</p>

<h3>Détails de l'erreur</h3>
<p>N'hésitez pas à fournir le code d'erreur et le message suivant à l'administrateur :</p>
<p><strong>Code : </strong> <?= $tplVars["code"];?></p>
<p><strong>Message : </strong><em><?= $tplVars["message"];?></em></p>

<a href="index.php">Retour à l'accueil du site</a>
</main>
</body>
</html>