<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>chat</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= $tplVars['WWW_URL']; ?>assets/css/style.css">
</head>
<body>
<header class="header">
    <div class="test">
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
        <div class="container"><a href="<?= $tplVars['WWW_URL']; ?>" class="navbar-brand text-uppercase font-weight-bold">Chat</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                <?php if(isset($_SESSION['user'])): ?>
                <li class="nav-item"><span class="nav-link text-uppercase font-weight-bold">Bonjour, <?= $_SESSION['user']['Nickname']; ?></span></li>
                <li class="nav-item"><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=profil" class="nav-link text-uppercase font-weight-bold">Mon profil</a></li>
                <li class="nav-item"><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=logout" class="nav-link text-uppercase font-weight-bold">Déconnection</a></li>
                <?php else: ?>
                <li class="nav-item"><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=form" class="nav-link text-uppercase font-weight-bold">Création de compte</a></li>
                <li class="nav-item"><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user" class="nav-link text-uppercase font-weight-bold">Identification</a></li>
                <?php endif; ?></ul>
            </div>
        </div>
    </nav>
    <!-- <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
        <div class="container"><a href="<?= $tplVars['WWW_URL']; ?>" class="navbar-brand text-uppercase font-weight-bold">Chat</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                <?php if(isset($_SESSION['user'])): ?>
                <li class="nav-item"><span class="nav-link text-uppercase font-weight-bold">Bonjour, <?= $_SESSION['user']['Nickname']; ?></span></li>
                <li class="nav-item"><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=profil" class="nav-link text-uppercase font-weight-bold">Mon profil</a></li>
                <li class="nav-item"><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=logout" class="nav-link text-uppercase font-weight-bold">Déconnection</a></li>
                <?php else: ?>
                <li class="nav-item"><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user&task=form" class="nav-link text-uppercase font-weight-bold">Création de compte</a></li>
                <li class="nav-item"><a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=user" class="nav-link text-uppercase font-weight-bold">Identification</a></li>
                <?php endif; ?></ul>
            </div>
        </div>
    </nav> -->
    </div>
</header>
   <fieldset>
   <?= $pageContent ?>
   </fieldset>
</body>
</html>